<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">

    <title>{{ $title }}</title>

    <style>
        @page {
            margin: 24px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9px;
            color: #111827;
        }

        h1 {
            margin: 0 0 6px;
            font-size: 16px;
            text-align: center;
        }

        .meta {
            margin-bottom: 14px;
            text-align: center;
            font-size: 8px;
            color: #4b5563;
        }

        .filters {
            margin-bottom: 12px;
            font-size: 8px;
        }

        .filters strong {
            margin-right: 4px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #9ca3af;
            padding: 5px;
            vertical-align: top;
        }

        th {
            background: #e5e7eb;
            font-weight: bold;
            text-align: center;
        }

        td {
            word-wrap: break-word;
        }

        .footer {
            margin-top: 14px;
            font-size: 8px;
            color: #6b7280;
            text-align: right;
        }
    </style>
</head>

<body>
    <h1>{{ $title }}</h1>

    <div class="meta">
        Generated: {{ $generatedAt->format('d-m-Y H:i:s') }}
        |
        Generated by: {{ $generatedBy }}
    </div>

    @if (!empty($filters))
        <div class="filters">
            <strong>Filter:</strong>

            @foreach ($filters as $key => $value)
                @if ($key !== 'format' && $value !== null && $value !== '')
                    {{ $key }}={{ $value }}@if (!$loop->last), @endif
                @endif
            @endforeach
        </div>
    @endif

    <table>
        <thead>
            <tr>
                @foreach ($headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>

        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $value)
                        <td>{{ $value }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td
                        colspan="{{ count($headings) }}"
                        style="text-align: center;"
                    >
                        Tidak ada data.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        SIAKAD — Laporan Akademik
    </div>
</body>
</html>